yeet

diff --git a/git-hooks/pre-push b/git-hooks/pre-push
--- a/git-hooks/pre-push
+++ b/git-hooks/pre-push
@@ -14,19 +14,26 @@ set -Eeuo pipefail
 #   <local ref> <local sha1> <remote ref> <remote sha1>
 #
 
-protected_branches=('trunk')
+# 1. git lfs
 
-IFS=' '
-while read local_ref local_sha remote_ref remote_sha
-do
-    for protected_branch in "${protected_branches[@]}"; do
-        if [[ $remote_ref == "refs/heads/$protected_branch" ]]; then
-            echo -en "\033[31mYou're about to push trunk, that is verboten!\033[0m"
-            echo
-            exit 1 # push will not execute
-        fi
-    done
-done
+command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\n[dev-env] ERROR: This repository is configured for Git LFS but 'git-lfs' was not found on your path. \n"; exit 2; }
+git lfs pre-push "$@"
 
-# nothing wrong, let push execute
+# 2. protected branch
+
+# protected_branches=('trunk')
+
+# IFS=' '
+# while read local_ref local_sha remote_ref remote_sha
+# do
+#     for protected_branch in "${protected_branches[@]}"; do
+#         if [[ $remote_ref == "refs/heads/$protected_branch" ]]; then
+#             echo -en "\033[31mYou're about to push trunk, that is verboten!\033[0m"
+#             echo
+#             exit 1 # push will not execute
+#         fi
+#     done
+# done
+
+# n. nothing wrong, let push execute
 exit 0
