feat(devenv): add editorconfig linting

diff --git a/bin/de-lint b/bin/de-lint
--- a/bin/de-lint
+++ b/bin/de-lint
@@ -4,6 +4,14 @@
 
 set -Eeuo pipefail
 
+# 0. editorconfig linting
+echo "[dev-env] Lint against .editorconfig except if the file is located inside third_party/"
+command -v editorconfig-checker >/dev/null 2>&1 || { echo >&2 "[dev-env] ERROR:
+'editorconfig-checker' was not found on your path"; exit 2; }
+
+# shellcheck disable=SC2038
+editorconfig-checker "${REPO_ROOT}"
+
 # 1. lint shell scripts
 echo "[dev-env] Linting shell scripts except if the file is located inside third_party/"
 command -v shellcheck >/dev/null 2>&1 || { echo >&2 "[dev-env] ERROR: 'shellcheck' was not found on your path"; exit 2; }
